CLASS zcl_di_test_dependency_2 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    INTERFACES zif_di_test_dependency_2.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_di_test_dependency_2 IMPLEMENTATION.
ENDCLASS.
